@Api_HostAddress = http://localhost:5158

### Get single employee
GET {{Api_HostAddress}}/api/employees/2
Accept: application/json

### Get employees (paged)
GET {{Api_HostAddress}}/api/employees?pageNumber=1&pageSize=10
Accept: application/json

### Get employees with filter and ordering
GET {{Api_HostAddress}}/api/employees?pageNumber=1&pageSize=10
Accept: application/json

### Get employees by project (paged)
GET {{Api_HostAddress}}/api/employees/projects/5?pageNumber=1&pageSize=10
Accept: application/json

### Create employee
POST {{Api_HostAddress}}/api/employees
Content-Type: application/json

{
  "firstName": "Ivan",
  "middleName": "Petrovich",
  "family": "Ivanov",
  "email": "ivan.ivanov@example.com",
  "role": 1
}

### Update employee (partial PATCH)
PATCH {{Api_HostAddress}}/api/employees/2
Content-Type: application/json

{
  "firstName": "Ivan Updated",
  "email": "ivan.updated@example.com"
}

### Delete employee
DELETE {{Api_HostAddress}}/api/employees/2
Accept: application/json
###
