// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DataContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251113125220_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_EMAIL");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_FAMILY");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_FIRST_NAME");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_MIDDLE_NAME");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EMPLOYEE_ROLE");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEES", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("CompanyExecutingName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_COMPANY_EXECUTING_NAME");

                    b.Property<string>("CompanyOrderingName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_COMPANY_ORDERING_NAME");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_END_DATE");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_MANAGER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_NAME");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_PRIORITY");

                    b.Property<DateOnly>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_START_DATE")
                        .HasDefaultValueSql("date('now')");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("PROJECTS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EMPLOYEE_ID");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PROJECT_MEMBERS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.HasOne("Domain.Models.Employee", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PROJECTS_EMPLOYEES");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.Models.ProjectMember", b =>
                {
                    b.HasOne("Domain.Models.Employee", "Employee")
                        .WithMany("Memberships")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EMPLOYEES_MEMBERS");

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROJECTS_MEMBERS");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.Navigation("ManagedProjects");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
