// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DataContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_EMAIL")
                        .UseCollation("NOCASE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_FIRST_NAME")
                        .UseCollation("NOCASE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_LAST_NAME")
                        .UseCollation("NOCASE");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMPLOYEE_MIDDLE_NAME")
                        .UseCollation("NOCASE");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EMPLOYEE_ROLE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_EMPLOYEES_EMPLOYEE_EMAIL");

                    b.ToTable("EMPLOYEES", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("CompanyExecuting")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_COMPANY_EXECUTING_NAME")
                        .UseCollation("NOCASE");

                    b.Property<string>("CompanyOrdering")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_COMPANY_ORDERING_NAME")
                        .UseCollation("NOCASE");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_END_DATE");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_MANAGER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_NAME")
                        .UseCollation("NOCASE");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_PRIORITY");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_START_DATE");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("IX_PROJECTS_PROJECT_MANAGER_ID");

                    b.ToTable("PROJECTS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ProjectDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_DOCUMENT_ID");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_DOCUMENT_CONTENT_TYPE");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_DOCUMENT_ORIGINAL_FILE_NAME")
                        .UseCollation("NOCASE");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_DOCUMENT_STORED_FILE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_PROJECT_DOCUMENTS_PROJECT_ID");

                    b.ToTable("PROJECT_DOCUMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EMPLOYEE_ID");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PROJECT_MEMBERS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_ID");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_AUTHOR_ID");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("TASK_COMMENT")
                        .UseCollation("NOCASE");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_CREATED_AT");

                    b.Property<int?>("ExecutorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_EXECUTOR_ID");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_PRIORITY");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_PROJECT_ID");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("TASK_TITLE")
                        .UseCollation("NOCASE");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TASK_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_TASKS_TASK_AUTHOR_ID");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("IX_TASKS_TASK_EXECUTOR_ID");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_TASKS_TASK_PRIORITY");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_TASKS_TASK_PROJECT_ID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TASKS_TASK_STATUS");

                    b.ToTable("TASKS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.HasOne("Domain.Models.Employee", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PROJECTS_EMPLOYEES");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.Models.ProjectDocument", b =>
                {
                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROJECTS_DOCUMENTS");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.ProjectMember", b =>
                {
                    b.HasOne("Domain.Models.Employee", "Employee")
                        .WithMany("Memberships")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EMPLOYEES_MEMBERS");

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROJECTS_MEMBERS");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.WorkTask", b =>
                {
                    b.HasOne("Domain.Models.Employee", "Author")
                        .WithMany("AuthoredTasks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TASKS_AUTHOR");

                    b.HasOne("Domain.Models.Employee", "Executor")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TASKS_EXECUTOR");

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TASKS_PROJECTS");

                    b.Navigation("Author");

                    b.Navigation("Executor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("AuthoredTasks");

                    b.Navigation("ManagedProjects");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
